export const NAVIGATION_CLOSE_PAGE = 'NAVIGATION_CLOSE_PAGE';
export const NAVIGATION_OPEN_PAGE = 'NAVIGATION_OPEN_PAGE';
export const NAVIGATION_BROWSER_BACK = 'NAVIGATION_BROWSER_BACK';
export const NAVIGATION_CURRENT_ROUTE = 'NAVIGATION_CURRENT_ROUTE';